Test check 2WW

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,24 +1,20 @@
-#!/bin/bash
-
-root="$(git rev-parse --show-toplevel)"
-[ -d "$root" ] || exit 1
-
-owndir="$(cd "$(dirname "$0")"; pwd -P)"
-
-OS_NAME=$(uname)
-
-if [ "$OS_NAME" = "Darwin" ]; then
-  FIND_ARGS="-perm +0111"
+#!/bin/sh
+# Check if this is the initial commit
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+echo "pre-commit: About to create a new commit..."
+against=HEAD
 else
-  FIND_ARGS="-executable"
+echo "pre-commit: About to create the first commit..."
+against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
-tmp_file="$root/.git/tmp-filelist.txt"
-git diff --name-only --cached --diff-filter=ACM | awk -v prefix="$root/" '{print prefix $0}' > "$tmp_file"
-
-echo "Processing import-optimizer script ..."
-"$owndir/import-optimizer" < "$tmp_file" || exit 1
-
-echo "Processing formatter script ..."
-"$owndir/formatter" < "$tmp_file" || exit 1
-cat $tmp_file | xargs git add
-rm "$tmp_file"
+# Use git diff-index to check for whitespace errors
+echo "pre-commit: Testing for whitespace errors..."
+if ! git diff-index --check --cached $against
+then
+echo "pre-commit: Aborting commit due to whitespace errors"
+exit 1
+else
+echo "pre-commit: No whitespace errors :)"
+exit 0
+fi
